version: '3.9'

services:
  dennisnodemembertask:
    container_name: dennisnodemembertask
    image: dennisnodemembertask
    build: .
    command: npm start
    ports:
      - "8000:8000"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dbnodemembertask;Database=postgres;Username=postgres;Password=postgres"
      # WATCHPACK_POLLING: "true"
    depends_on:
      - dbnodemembertask
    x-develop:
      watch:
        - action: rebuild
          path: .  
          ignore:
            - node_modules/
  dbnodemembertask:
    container_name: dbnodemembertask
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seeds:/docker-entrypoint-initdb.d

volumes:
  pgdata: {}